name: test-backend

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.1"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: sudo apt install inotify-tools -y
      - run: gleam deps download
      - run: gleam format --check src test
      - run: gleam test
