name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.11.1"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: cd backend/ && gleam deps download
      - run: cd backend/ && gleam format --check src test
      - run: cd backend/ && gleam test
